### ISSUE TITLE
What is the proper way to index a document?

### ISSUE THREAD

**Issue by jnovak-SM2Dev** [codemask-labs/nestjs-elasticsearch#203]
What is the proper way to index a document with this plugin? I don't see it in the example.

**Comment by jnovak-SM2Dev** [comment]
I assume you import the main service like this:

```
private readonly elasticsearchService: ElasticsearchService,
```

And then use it like this:

```
await this.elasticsearchService.getBaseService().index({
      index: 'animals',
      document: animal,
    });
```

**Comment by adrianboratyn** [comment]
You are right, you need to use base service. We don't support indexing yet.

**Comment by jnovak-SM2Dev** [comment]
Sounds good. Thanks for getting back to me.
